version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./tests/_data:/docker-entrypoint-initdb.d
       - wp_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
       - "3308:3306"

   wordpress:
     depends_on:
       - db
     image: wordpress
     restart: always
     ports:
       - "1313:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - wordpress:/var/www/html
       - .:/var/www/html/wp-content/plugins/better-wp-reviews

   chrome:
     image: selenium/standalone-chrome-debug:3.141.59-20201119
     volumes:
       - /dev/shm:/dev/shm
     ports:
       - "5900:5900"
       - "4444:4444"

volumes:
    wp_db_data: {}
    wordpress: {}